name: CI

on:
  push:
    tags:
      - build-linux-*

jobs:
  linux:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: |
        sudo apt-get install build-essential
        git submodule init
        git submodule update
    - name: Build
      run: |
        mkdir tmp
        cd tmp
        cmake ..
        make
        cd ..
        mkdir build
        mv tmp/COLLADA2GLTF-bin build/COLLADA2GLTF-bin
        mv tmp/libCOLLADA2GLTF.a build/libCOLLADA2GLTF.a
        zip -r build.zip build
    - uses: actions/upload-artifact@v1
      with:
        name: build
        path: build.zip